WebLayer/Controllers/OrderDetailsController.cs
using Business_layer.AppServices;
using Business_layer.ViewModel;
using Data_access_Layer;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
   // [Authorize]
    public class OrderDetailsController : Controller
    {
        OrderDetailsAppService orderDetailsAppService = new OrderDetailsAppService();
        // GET: Order
        public ActionResult Index()
        {
            return View(orderDetailsAppService.GetAllOrderDetails());
        }

        public ActionResult Create() => View();

        [HttpPost]
        public ActionResult Create(OrderDetailsViewModel newOrderDetail)
        {
            if (ModelState.IsValid == false)
                return View(newOrderDetail);
            orderDetailsAppService.SaveNewOrdeDetails(newOrderDetail);
            return RedirectToAction("Index");
        }


        public ActionResult Edit(int Id)
        {
            var order = orderDetailsAppService.GetOrderDetails(Id);
            return View(order);
        }

        [HttpPost]
        public ActionResult Edit(OrderDetailsViewModel newOrderDetail)
        {
            if (ModelState.IsValid)
            {
                orderDetailsAppService.UpdatOrdeDetails(newOrderDetail);
              //  orderDetailsAppService.SaveNewOrdeDetails(newOrderDetail);
                return RedirectToAction("Index");
            }
            else
            {
                return View(newOrderDetail);
            }
        }
        /*[HttpGet]
        public ActionResult Delete()
        {
            return View();
        }*/
        [HttpPost]
            public ActionResult Delete(int id)
        {

            orderDetailsAppService.DeleteOrderDetails(id);
            return RedirectToAction("Index");
        }



        public ActionResult Details(int Id)
        {
            var order = orderDetailsAppService.GetOrderDetails(Id);
            return View(order);
        }

     

      




    }
}

WebLayer/Views/Admin/AddAdmin.cshtml
@model Business_layer.ViewModel.RegisterViewodel

@{
    ViewBag.Title = "AddAdmin";
}

<h2>AddAdmin</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegisterViewodel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebLayer/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";

}

<h2>Index</h2>
<ul>
    <li>@Html.ActionLink("Category", "index", "Category")</li>

    <li>@Html.ActionLink("Product", "Index", "Product")</li>
    <li> @Html.ActionLink("Order", "Index", "Order") </li>
    <li>@Html.ActionLink("OrderDetalis", "Index", "OrderDetails")</li>
</ul>

WebLayer/Views/Admin/NewRole.cshtml
@model Business_layer.ViewModel.categoryViewModelcs
@{
    ViewBag.Title = "NewRole";
}

<h2>NewRole</h2>
@*<ul>
    @if (ViewBag.Error2 != null)
    {
        foreach (var item in ViewBag.Error2)
        {
            <li>@item</li>
        }
    }
    <li>@ViewBag.Error1</li>
</ul>
 *@
@using (Html.BeginForm())
{
    @Html.Label("Role Name")
    @Html.Editor("RoleName")

    <input type="submit" />
}